### PR TITLE
Test README.md using skeptic

### LINKED ISSUE #22: Test README examples with rust-skeptic
It's pretty easy to forget to update the code examples in `README.md` when the API changes, which means the first usage example new users see might not even be correct. In order to catch such issues as quickly as possible, we should setup [rust-skeptic](https://github.com/budziq/rust-skeptic). Doing so will ensure that code examples in the README will get tested as part of `cargo test` (and therefor as part of CI builds) just like any other doc test.

### PR DESCRIPTION
**Pull request by mvesterli**
Resolves #22

### CODE REVIEW

**Comment by mvesterli** [comment]
That's odd. I can't reproduce that test failure.

**Comment by randomPoison** [comment]
I'll try restarting the build and see if that helps, it might have just been a transient error.

**Comment by randomPoison** [comment]
I get a very strange error if I try to run this on my computer 😰 

```
     Running target\debug\deps\skeptic-de4dc05258de9635.exe

running 1 test
error[E0514]: found crate `amethyst_editor_sync` compiled by an incompatible version of rustc
 --> C:\Users\David\AppData\Local\Temp\rust-skeptic.UgBygEp6Kd1I\test.rs:4:1
  |
4 | extern crate amethyst_editor_sync;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: please recompile that crate using this compiler (rustc 1.29.2 (17a9dc751 2018-10-05))
  = note: the following crate versions were found:
          crate `amethyst_editor_sync` compiled by rustc 1.28.0 (9634041f0 2018-07-30): \\?\D:\GitHub\amethyst-editor-sync\target\debug\deps\libamethyst_editor_sync-1122c0d0dbdddbc9.rlib

error: aborting due to previous error

For more information about this error, try `rustc --explain E0514`.
test readme_sect_setup_and_usage_line_19 ... FAILED

failures:

---- readme_sect_setup_and_usage_line_19 stdout ----
thread 'readme_sect_setup_and_usage_line_19' panicked at 'Command failed:
"rustc" "C:\\Users\\David\\AppData\\Local\\Temp\\rust-skeptic.UgBygEp6Kd1I\\test.rs" "--verbose" "--crate-type=bin" "-L" "D:\\GitHub\\amethyst-editor-sync\\target\\debug" "-L" "D:\\GitHub\\amethyst-editor-sync\\target\\debug\\deps" "--target" "x86_64-pc-windows-msvc" "--extern" "serde=D:\\GitHub\\amethyst-editor-sync\\target\\debug\\deps\\libserde-c9aa0a7ffa836b0c.rlib" "--extern" "serde_json=D:\\GitHub\\amethyst-editor-sync\\target\\debug\\deps\\libserde_json-340ac4e4cfdef4d8.rlib" "--extern" "skeptic=D:\\GitHub\\amethyst-editor-sync\\target\\debug\\deps\\libskeptic-22aeb1995579debc.rlib" "--extern" "amethyst_editor_sync=D:\\GitHub\\amethyst-editor-sync\\target\\debug\\deps\\libamethyst_editor_sync-1122c0d0dbdddbc9.rlib" "--extern" "amethyst=D:\\GitHub\\amethyst-editor-sync\\target\\debug\\deps\\libamethyst-152edb759bf28791.rlib" "--extern" "log=D:\\GitHub\\amethyst-editor-sync\\target\\debug\\deps\\liblog-df30a9cac0fb6ac6.rlib" "--extern" "log_once=D:\\GitHub\\amethyst-editor-sync\\target\\debug\\deps\\liblog_once-cf548c3692000d11.rlib" "--extern" "env_logger=D:\\GitHub\\amethyst-editor-sync\\target\\debug\\deps\\libenv_logger-fddf9d1ad88a6b78.rlib" "--extern" "crossbeam_channel=D:\\GitHub\\amethyst-editor-sync\\target\\debug\\deps\\libcrossbeam_channel-10405ac93be3c9b3.rlib" "-o" "C:\\Users\\David\\AppData\\Local\\Temp\\rust-skeptic.UgBygEp6Kd1I\\out.exe"', C:\Users\David\.cargo\registry\src\github.com-1ecc6299db9ec823\skeptic-0.13.3\lib.rs:835:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    readme_sect_setup_and_usage_line_19

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test skeptic'
```

I'm gonna try to dig into this and see what's happening.

**Comment by randomPoison** [comment]
Oh shit, I bet I know what's going on: I think the travis cache is keeping stuff it shouldn't. I'm going to remove caching on master, which should fix your PR.

**Comment by randomPoison** [comment]
@mvesterli looks like you might have to merge master into your branch in order to get the fix, sorry.

**Pull request merged**
